# Generated by Django 3.2.17 on 2023-02-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawler',
            name='expected_total',
            field=models.IntegerField(default=0, help_text='예상되는 이미지 수집 수', verbose_name='TOTAL IMAGE'),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_total',
            field=models.IntegerField(default=0, help_text='예상되는 이미지 수집 수', verbose_name='TOTAL IMAGE'),
        ),
        migrations.AlterField(
            model_name='image',
            name='save_path',
            field=models.TextField(default='./images', help_text='이미지가 저장되어 있는 path', verbose_name='SAVE PATH'),
        ),
    ]
