# Generated by Django 3.2.17 on 2023-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20230203_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawler',
            name='collected',
            field=models.IntegerField(default=1, help_text='수집한 이미지/단어 개수', verbose_name='COLLECTED'),
        ),
        migrations.AlterField(
            model_name='crawler',
            name='expected_total',
            field=models.IntegerField(default=1, help_text='예상되는 이미지 수집 수', verbose_name='TOTAL IMAGE'),
        ),
    ]
